abbr cb 'cargo build'
abbr ct 'cargo test'
abbr cr 'cargo run'

abbr g 'git'
abbr ga 'git add'
abbr gcm 'git commit --verbose'
abbr gca 'git commit --verbose --amend'
abbr gcb 'git checkout -b'
abbr gco 'git checkout'
abbr gd 'git diff'
abbr gf 'git fetch'
abbr gds 'git diff --staged'
abbr gs 'git status'
abbr gl 'git log'
abbr gp 'git pull'
abbr glgp 'git log --stat --patch'
abbr grb 'git rebase'
abbr grs 'git restore'
