#!/usr/bin/env bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

#boot picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
fi

leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

#set background
#if [ -x "$(command -v feh)" ]; then
#  feh --bg-scale $SCRIPTPATH/background.jpg
#fi

# Set the background colour
hsetroot -solid '#222222'

polybar &

alacritty -e /usr/bin/fish &

