
[[ -f ~/.bashrc ]] && . ~/.bashrc
if [ -e /home/tekul/.nix-profile/etc/profile.d/nix.sh ]; then . /home/tekul/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
. "$HOME/.cargo/env"

export RUSTY_V8_MIRROR="$HOME/code/rusty_v8"

export FLYCTL_INSTALL="/home/tekul/.fly"
export PATH="$FLYCTL_INSTALL/bin:$PATH"

#if [ -z "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
#  exec startx
#fi
